### ISSUE TITLE
Link to tutorials ends in 404

### ISSUE THREAD

**Issue by froschdesign** [laminas/laminas.github.io#4]
The repository for tutorials is not ported to Laminas. I see two options to solve the problem:

* migrate the tutorials repository to Laminas
* remove the outdated link from JSON file (add later to correct one)

See: https://docs.laminas.dev/components/#learn

**Comment by weierophinney** [comment]
I'm in the process of porting the repository over.

I'm not entirely sure about a few things, though:

- Should it have the MVC or Components styling? The majority of it is information on getting started building an MVC application, as well as migrating MVC applications from v2 to v3.
- But it also has some component-specific tutorials (event manager, setting up database adapters)
- Shouldn't tutorials be the _first_ thing people see when hitting the landing pages?

Since the majority of content is MVC-related, I'm going to style it using that selector for now. We may want to break the tutorials into multiple repos (components-tutorials, mvc-tutorials) and/or move the component-specific tutorials into their individual components.

**Comment by weierophinney** [comment]
Fixed!
